services:
  postgres:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=chirpy
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U postgres' ]
      interval: 5s
      timeout: 5s
      retries: 5

  chirpy:
    image: kftlfd/chirpy:1.0
    build: .
    ports:
      - 8080:8080
    volumes:
      - ./public:/app/public
    environment:
      - PLATFORM=prod
      - HOST=0.0.0.0
      - DB_URL=postgres://postgres:postgres@postgres:5432/chirpy?sslmode=disable
      - SERVER_SECRET=server-secret
      - POLKA_KEY=polka-key
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  db-data:
